insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("LG그램", "컴퓨터", 1500000, "LG전자", 30, "15인치 노트북")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("삼성 노트S", "컴퓨터", 1700000, "삼성전자", 20, "펜으로 필기하는 노트북")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("아이폰", "컴퓨터", 1000000, "애플", 40, "아이폰 11pro")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("아이패드", "컴퓨터", 700000, "애플", 37, "아이패드 에어3")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("에어팟", "컴퓨터", 150000, "애플", 52, "무선 충전 가능")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("버즈", "컴퓨터", 130000, "삼성전자", 47, "안드로이드 무선 이어폰")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("식기세척기", "컴퓨터", 500000, "LG전자", 10, "99.9% 살균 가능")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("전자레인지", "컴퓨터", 300000, "삼성전자", 9, "1000w")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("가스레인지", "컴퓨터", 300000, "LG전자", 7, "화구 3개")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("김치냉장고", "컴퓨터", 1200000, "삼성전자", 11, "효도 필수품")
